services:
  patterpunk:
    build: patterpunk
    restart: unless-stopped
    volumes:
      - ./patterpunk/src:/app
    environment:
      # Flush print statements immediately
      PYTHONUNBUFFERED: 1
      PP_OPENAI_API_KEY: "${OPENAI_API_KEY}"
      PP_AWS_REGION: "${AWS_REGION}"
      PP_AWS_ACCESS_KEY_ID: "${AWS_ACCESS_KEY_ID}"
      PP_AWS_SECRET_ACCESS_KEY: "${AWS_SECRET_ACCESS_KEY}"
