import os

from openai import OpenAI

DEFAULT_MODEL = os.getenv("PP_DEFAULT_MODEL") or "gpt-4o-mini"
DEFAULT_TEMPERATURE = os.getenv("PP_DEFAULT_TEMPERATURE") or 1.0
DEFAULT_TOP_P = os.getenv("PP_DEFAULT_TOP_P") or 1.0
DEFAULT_FREQUENCY_PENALTY = os.getenv("PP_DEFAULT_FREQUENCY_PENALTY") or 0.0
DEFAULT_PRESENCE_PENALTY = os.getenv("PP_DEFAULT_PRESENCE_PENALTY") or 0.0
MAX_RETRIES = os.getenv("PP_MAX_RETRIES") or 6
OPENAI_MAX_RETRIES = os.getenv("PP_OPENAI_MAX_RETRIES") or MAX_RETRIES

AWS_REGION = os.getenv("PP_AWS_REGION", "us-east-1")
AWS_ACCESS_KEY_ID = os.getenv("PP_AWS_ACCESS_KEY_ID", None)
AWS_SECRET_ACCESS_KEY = os.getenv("PP_AWS_SECRET_ACCESS_KEY", None)

OPENAI_API_KEY = os.getenv("PP_OPENAI_API_KEY", None)
if OPENAI_API_KEY:
    openai = OpenAI(api_key=OPENAI_API_KEY)
