import os

DEFAULT_MODEL = os.getenv('PP_DEFAULT_MODEL') or 'gpt-3.5-turbo'
DEFAULT_TEMPERATURE = os.getenv('PP_DEFAULT_TEMPERATURE') or 1.
DEFAULT_TOP_P = os.getenv('PP_DEFAULT_TOP_P') or 1.
DEFAULT_FREQUENCY_PENALTY = os.getenv('PP_DEFAULT_FREQUENCY_PENALTY') or 0.
DEFAULT_PRESENCE_PENALTY = os.getenv('PP_DEFAULT_PRESENCE_PENALTY') or 0.
OPENAI_MAX_RETRIES = os.getenv('PP_OPENAI_MAX_RETRIES') or 5