import os
from typing import Optional

from ..defaults import DEFAULT_TEMPERATURE, DEFAULT_TOP_P

GOOGLE_APPLICATION_CREDENTIALS = os.getenv("PP_GOOGLE_APPLICATION_CREDENTIALS", None)
GEMINI_REGION = os.getenv("PP_GEMINI_REGION", "us-central1")
GEMINI_PROJECT = os.getenv("PP_GEMINI_PROJECT", None)
GOOGLE_DEFAULT_TEMPERATURE = os.getenv(
    "PP_GOOGLE_DEFAULT_TEMPERATURE", DEFAULT_TEMPERATURE
)
GOOGLE_DEFAULT_TOP_P = os.getenv("PP_GOOGLE_DEFAULT_TOP_P", DEFAULT_TOP_P)
GOOGLE_DEFAULT_TOP_K = os.getenv("PP_GOOGLE_DEFAULT_TOP_K", None)
GOOGLE_DEFAULT_MAX_TOKENS = os.getenv("PP_GOOGLE_DEFAULT_MAX_TOKENS", None)


def is_google_available() -> bool:
    return GOOGLE_APPLICATION_CREDENTIALS is not None and GEMINI_PROJECT is not None
